apiVersion: staticcontent.operators.openshift.io/v1alpha1
kind: Config
metadata:
  name: cluster
spec:
  platform: gcp
  config:
    telemeterServerURL: telemeterServerURL.com
    identityAttrEmail: identityAttrEmail
    identityAttrID: identityAttrID
    identityAttrName: identityAttrName
    identityAttrPreferredUsername: identityAttrPreferredUsername
    identityBindName: identityBindName
    identityURL: identityURL
    identityName: identityName
    identityMappingMethod: identityMappingMethod
    valeroOperatorImage: quay.io/openshift-sre/managed-velero-operator:v0.1.35-49347f0
    # TODO: think something better
    osdLdapCA: asdasd